version: '3.7'
services:
  app:
    container_name: "ytdl-api"
    build:
      context: .
      target: dev
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - "./media/:/app/media"
    develop:
      watch:
        - action: "rebuild"
          path: poetry.lock
        - action: "sync"
          path: "./ytdl_api"
          target: "/app/ytdl_api"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - default
  tests:
    container_name: "ytdl-api-pytest"
    command: 
        --cov --cov-report=xml:coverage_report/cov.xml
    build:
      context: .
      target: test
    volumes:
      - "./coverage_report:/app/coverage_report"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 220M
        reservations:
          cpus: '0.25'
          memory: 20M
