version: '3.7'
services:
  ytdl-api:
    container_name: "ytdl-api"
    build:
      context: .
      target: dev
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - "./ytdl_api/:/app/ytdl_api"
      - "./media/:/app/media"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - default
