version: '3.7'
services:
  ytdl-api-db:
    container_name: "ytdl-api-db"
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ytdl-api-db-data:/var/lib/postgresql/data
    networks:
      - default
  ytdl-api:
    container_name: "ytdl-api"
    build:
      context: .
      target: dev
    ports:
      - 8000:80
    env_file:
      - .env
    volumes:
      - "./ytdl_api/:/app/ytdl_api"
      - "./media/:/app/media"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - default
  ytdl-api-testing:
    container_name: "ytdl-api-pytest"
    build: 
      context: .
      target: test
    env_file:
      - .env
    volumes:
      - "./ytdl_api/:/app/ytdl_api"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 220M
        reservations:
          cpus: '0.25'
          memory: 20M
volumes:
  ytdl-api-db-data: