name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ytdl_api/**
      - tests/**
      - uv.lock
      - .github/workflows/**
  workflow_dispatch:
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: ruff
    steps:
      - name: Install ffmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
      #----------------------------------------------
      #  -----  install uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync --frozen
      #----------------------------------------------
      #    run test suite and output coverage file
      #----------------------------------------------
      - name: Run Pytest
        run: uv run pytest --cov=${{ github.workspace }} --cov-report=xml
      #----------------------------------------------
      #             upload coverage stats
      # (requires CODECOV_TOKEN in repository secrets)
      #----------------------------------------------
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}